# Generated by Django 6.0.2 on 2026-02-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_orchestration', '0005_add_deployment_session_human_input_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deploymentsession',
            name='unique_deployment_session',
        ),
        migrations.RenameIndex(
            model_name='deploymentexecution',
            new_name='agent_orche_deploym_0e227f_idx',
            old_name='deploy_exec_session_created_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentexecution',
            new_name='agent_orche_executi_85fed1_idx',
            old_name='deploy_exec_exec_id_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentexecution',
            new_name='agent_orche_status_039904_idx',
            old_name='deploy_exec_status_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentsession',
            new_name='agent_orche_deploym_e7b5bb_idx',
            old_name='deploy_session_deploy_sess_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentsession',
            new_name='agent_orche_deploym_bc4915_idx',
            old_name='deploy_session_deploy_act_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentsession',
            new_name='agent_orche_is_acti_4de63f_idx',
            old_name='deploy_session_active_act_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowallowedorigin',
            new_name='agent_orche_deploym_939f28_idx',
            old_name='agent_orch_deployment_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowallowedorigin',
            new_name='agent_orche_origin_419745_idx',
            old_name='agent_orch_origin_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdeployment',
            new_name='agent_orche_project_abccb4_idx',
            old_name='agent_orch_project_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdeployment',
            new_name='agent_orche_is_acti_3109bf_idx',
            old_name='agent_orch_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdeploymentrequest',
            new_name='agent_orche_deploym_61fa24_idx',
            old_name='agent_orch_deployment_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdeploymentrequest',
            new_name='agent_orche_origin_291463_idx',
            old_name='agent_orch_origin_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdeploymentrequest',
            new_name='agent_orche_status_c6c798_idx',
            old_name='agent_orch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdeploymentrequest',
            new_name='agent_orche_session_6f59e6_idx',
            old_name='agent_orch_session_created_idx',
        ),
        migrations.AddField(
            model_name='workflowdeployment',
            name='chatbot_subtitle',
            field=models.CharField(default='Powered by AICC IntelliDoc', help_text='Subtitle displayed below the chatbot title', max_length=200),
        ),
        migrations.AddField(
            model_name='workflowdeployment',
            name='chatbot_title',
            field=models.CharField(default='AI Assistant', help_text='Title displayed in the chatbot header', max_length=100),
        ),
        migrations.AddField(
            model_name='workflowdeployment',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Optional URL to a logo image displayed in the header', null=True),
        ),
        migrations.AddField(
            model_name='workflowdeployment',
            name='primary_color',
            field=models.CharField(default='#0b3b66', help_text='Primary color for header and user messages (hex format)', max_length=7),
        ),
        migrations.AddField(
            model_name='workflowdeployment',
            name='secondary_color',
            field=models.CharField(default='#1e5a8a', help_text='Secondary color for gradient effects (hex format)', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='deploymentsession',
            unique_together={('deployment', 'session_id')},
        ),
    ]
