# Generated by Django 6.0.3 on 2026-04-02 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_orchestration', '0006_add_chatbot_customization_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdeployment',
            name='file_uploads_enabled',
            field=models.BooleanField(default=False, help_text='Whether end-users can upload files in the chatbot'),
        ),
        migrations.AlterField(
            model_name='workflowdeployment',
            name='primary_color',
            field=models.CharField(default='#78b2e8', help_text='Primary color for header and user messages (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='workflowdeployment',
            name='secondary_color',
            field=models.CharField(default='#3a6d98', help_text='Secondary color for gradient effects (hex format)', max_length=7),
        ),
        migrations.CreateModel(
            name='DeploymentSessionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('storage_path', models.CharField(help_text='Path in default_storage', max_length=500)),
                ('provider', models.CharField(help_text='LLM provider the file was uploaded to', max_length=20)),
                ('provider_file_id', models.CharField(help_text='File ID from the LLM provider API', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='agent_orchestration.deploymentsession')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
