# Generated by Django 6.0.3 on 2026-04-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_orchestration', '0007_workflowdeployment_file_uploads_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsessionfile',
            name='extracted_text',
            field=models.TextField(blank=True, default='', help_text='Extracted text for file types not supported by provider File API'),
        ),
        migrations.AlterField(
            model_name='deploymentsessionfile',
            name='provider_file_id',
            field=models.CharField(blank=True, default='', help_text='File ID from the LLM provider API', max_length=500),
        ),
    ]
