# Generated by Django 6.0.3 on 2026-04-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_orchestration', '0008_deploymentsessionfile_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdeployment',
            name='font_color',
            field=models.CharField(default='#1e293b', help_text='Font color for chatbot text (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='workflowdeployment',
            name='primary_color',
            field=models.CharField(default='#ffffff', help_text='Primary color for header and user messages (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='workflowdeployment',
            name='secondary_color',
            field=models.CharField(default='#ffffff', help_text='Secondary color for gradient effects (hex format)', max_length=7),
        ),
    ]
