# Generated by Django 6.0.4 on 2026-04-18 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_orchestration', '0009_workflowdeployment_font_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdeployment',
            name='public_url_auth_enabled',
            field=models.BooleanField(default=False, help_text='When true, end-users must log in with the credentials below before chatting'),
        ),
        migrations.AddField(
            model_name='workflowdeployment',
            name='public_url_enabled',
            field=models.BooleanField(default=False, help_text='Expose a hosted chat page at /chat/<project_id>'),
        ),
        migrations.AddField(
            model_name='workflowdeployment',
            name='public_url_password_hash',
            field=models.CharField(blank=True, default='', editable=False, help_text='PBKDF2 hash of the public chat password; never exposed via API', max_length=256),
        ),
        migrations.AddField(
            model_name='workflowdeployment',
            name='public_url_password_version',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Bumps on every password save — invalidates every live login token immediately'),
        ),
        migrations.AddField(
            model_name='workflowdeployment',
            name='public_url_username',
            field=models.CharField(blank=True, default='', help_text='Shared username for the public chat page (when auth is enabled)', max_length=150),
        ),
        migrations.AlterField(
            model_name='workflowdeployment',
            name='font_color',
            field=models.CharField(default='#000000', help_text='Font color for chatbot text (hex format)', max_length=7),
        ),
        migrations.CreateModel(
            name='DeploymentPublicLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username_attempted', models.CharField(max_length=150)),
                ('success', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_login_attempts', to='agent_orchestration.workflowdeployment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deployment', 'created_at'], name='agent_orche_deploym_95f8d4_idx'), models.Index(fields=['ip_address', 'created_at'], name='agent_orche_ip_addr_edaee8_idx')],
            },
        ),
    ]
