# Generated by Django 6.0.6 on 2026-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_orchestration', '0010_workflowdeployment_public_url_auth_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowdeployment',
            name='initial_greeting',
            field=models.CharField(default='Hi! I am your AI assistant.', help_text='Initial greeting message shown by the embedded chatbot', max_length=2500),
        ),
    ]
