# Generated by Django 6.0.3 on 2026-03-20 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_project_document_folder_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.CharField(choices=[('google_drive', 'Google Drive'), ('sharepoint', 'SharePoint')], help_text='MCP server type', max_length=20)),
                ('encrypted_credentials', models.TextField(help_text='Encrypted credentials JSON using project-specific encryption')),
                ('server_config', models.JSONField(blank=True, default=dict, help_text='Server configuration (site URLs, folder paths, etc.)')),
                ('credential_name', models.CharField(blank=True, help_text="Optional descriptive name for the credential (e.g., 'Production Credentials')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this credential is active and should be used')),
                ('is_validated', models.BooleanField(default=False, help_text='Whether this credential has been validated with the server')),
                ('validation_error', models.TextField(blank=True, help_text='Last validation error message, if any')),
                ('last_validated_at', models.DateTimeField(blank=True, help_text='When the credential was last validated', null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this credential has been used')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When the credential was last used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='experimentmetric',
            new_name='users_exper_project_ca7b67_idx',
            old_name='users_exper_project_exper_created_idx',
        ),
        migrations.RenameIndex(
            model_name='experimentmetric',
            new_name='users_exper_project_b6a4e6_idx',
            old_name='users_exper_project_created_idx',
        ),
        migrations.RenameIndex(
            model_name='experimentmetric',
            new_name='users_exper_experim_581bb5_idx',
            old_name='users_exper_experiment_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowevaluation',
            new_name='users_workf_workflo_153240_idx',
            old_name='users_workf_workflo_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowevaluation',
            new_name='users_workf_evaluat_f36f91_idx',
            old_name='users_workf_evaluat_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowevaluation',
            new_name='users_workf_created_75228b_idx',
            old_name='users_workf_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowevaluationresult',
            new_name='users_workf_evaluat_332a40_idx',
            old_name='users_workf_evaluat_row_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowevaluationresult',
            new_name='users_workf_evaluat_9abc46_idx',
            old_name='users_workf_evaluat_sta_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowevaluationresult',
            new_name='users_workf_average_826a4b_idx',
            old_name='users_workf_average_idx',
        ),
        migrations.AddField(
            model_name='projectdocumentsummary',
            name='citation',
            field=models.JSONField(blank=True, default=dict, help_text='Bibliographic metadata for the document (title, authors, year, DOI, etc.)'),
        ),
        migrations.AddField(
            model_name='projectdocumentsummary',
            name='memory',
            field=models.JSONField(blank=True, default=list, help_text='Accumulated agent insights from tool calls'),
        ),
        migrations.AlterField(
            model_name='intellidocproject',
            name='preserve_original_folder_structure',
            field=models.BooleanField(default=False, help_text='When enabled, uses LLM-based folder organization (based on per-document short summaries) instead of filename/path auto-classification'),
        ),
        migrations.AlterField(
            model_name='workflowexecutionmessage',
            name='message_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('workflow_start', 'Workflow Start'), ('workflow_end', 'Workflow End'), ('group_chat_summary', 'Group Chat Summary'), ('system', 'System'), ('error', 'Error'), ('reflection_feedback', 'Reflection Feedback'), ('reflection_revision', 'Reflection Revision'), ('reflection_final', 'Reflection Final'), ('tool_plan', 'Tool Plan'), ('tool_notebook', 'Tool Notebook Entry'), ('reflection_iteration', 'Reflection Iteration')], default='chat', max_length=20),
        ),
        migrations.AddIndex(
            model_name='projectdocumentfolderorganization',
            index=models.Index(fields=['document'], name='users_proje_documen_8576fb_idx'),
        ),
        migrations.AddField(
            model_name='mcpservercredential',
            name='created_by',
            field=models.ForeignKey(help_text='User who added this credential', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mcpservercredential',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_server_credentials', to='users.intellidocproject'),
        ),
        migrations.AddIndex(
            model_name='mcpservercredential',
            index=models.Index(fields=['project', 'server_type', 'is_active'], name='users_mcpse_project_5a5bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpservercredential',
            index=models.Index(fields=['project', 'is_active'], name='users_mcpse_project_40f017_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mcpservercredential',
            unique_together={('project', 'server_type')},
        ),
    ]
