# Generated by Django 6.0.4 on 2026-04-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_add_analytics_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvectorstatus',
            name='rag_indexed',
            field=models.BooleanField(default=False, help_text='True once the document has been embedded and inserted into Milvus. False for summary-only processing (backfill candidate when the project RAG toggle is re-enabled).'),
        ),
        migrations.AddField(
            model_name='intellidocproject',
            name='rag_enabled',
            field=models.BooleanField(default=True, help_text='Index documents into Milvus for DocAware/RAG search. When off, Start Processing only generates summaries; agent tool-calling still works, DocAware queries return empty.'),
        ),
    ]
